name: FancyMorphs
description: $description
author: OliverHD
version: $version
main: de.oliver.fancymorphs.FancyMorphs
api-version: 1.20
folia-supported: true
load: POSTWORLD
depend:
  - FancyNpcs

commands:
  FancyMorphs:
    permission: FancyMorphs.admin
  Morph:
    permission: FancyMorphs.morph
  Unmorph:
    permission: FancyMorphs.morph